---
title: "**Capstone project details**"
output: html_document
---
#**Introduction:** 
Analyze the data and outcomes associated with historical fine needle aspiration (FNA) biopsy results to predict if, based on attributes obtained from imaging results, a breast tumor is benign or malignant. If malignant, predict the likelihood of reoccurrence within a 24 month period. 	

#**Who’s the customer:** 
Doctors, patients 

#**What will they do with this information:**
Doctors and patients could use this information as input when determining the next step in achieving a diagnosis and treatment plan. For example, if analysis shows that tumors with a certain radius and a certain thickness are benign 99% of the time, and an image test of the tumor confirms attributes within the range, the decision may be to not perform a biopsy at this time. Or if the percentage is more like 50% chance of being malignant, maybe they perform an FNA or surgical biopsy.

#**Possible limitations:** 
Biopsies do not always confirm or deny malignancy, but this data does not appear to reflect this. There could be certain attributes that predict indeterminate results, but we will not be able to identify these attributes in this analysis. 

Additionally, there could be many other factors such as age and family history that are heavy influencers in the outcome, but are not present in these datasets.

Finally, for the reoccurrence prediction, treatment method is not known and is likely to be a factor.

#**Datasets:**
[DATASETS](https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/)
There are 3 comma delimited text file datasets that will be used for this analysis: Original, Diagnostic, and Prognostic. These datasets are independent of each other.   
  
    
**1. Original**   
	# of instances= 699  
	# of attributes = 11

Attribute Information: 

   #  Attribute                     Domain
   -- -----------------------------------------
   1. Sample code number            id number
   2. Clump Thickness               1 - 10
   3. Uniformity of Cell Size       1 - 10
   4. Uniformity of Cell Shape      1 - 10
   5. Marginal Adhesion             1 - 10
   6. Single Epithelial Cell Size   1 - 10
   7. Bare Nuclei                   1 - 10
   8. Bland Chromatin               1 - 10
   9. Normal Nucleoli               1 - 10
   10. Mitoses                      1 - 10
   11. Class:                      (2 for benign, 4 for malignant)

**2. Diagnostic**  
	# of instances= 569  
	# of attributes = 32 (ID, diagnosis, 30 real-valued input features)
Ten real-valued features are computed for each cell nucleus:

	a) radius (mean of distances from center to points on the perimeter)
	b) texture (standard deviation of gray-scale values)
	c) perimeter
	d) area
	e) smoothness (local variation in radius lengths)
	f) compactness (perimeter^2 / area - 1.0)
	g) concavity (severity of concave portions of the contour)
	h) concave points (number of concave portions of the contour)
	i) symmetry 
	j) fractal dimension ("coastline approximation" - 1)

**3. Prognostic**  
	# of instances = 198  
	# of attributes = 34 1)ID number 2) Outcome (R = recur, N = nonrecur)
3) Time (recurrence time if field 2 = R, disease-free time if 
	field 2	= N)
4-33) Ten real-valued features are computed for each cell nucleus:

	a) radius (mean of distances from center to points on the perimeter)
	b) texture (standard deviation of gray-scale values)
	c) perimeter
	d) area
	e) smoothness (local variation in radius lengths)
	f) compactness (perimeter^2 / area - 1.0)
	g) concavity (severity of concave portions of the contour)
	h) concave points (number of concave portions of the contour)
	i) symmetry 
	j) fractal dimension ("coastline approximation" - 1)

